import { BaseModel } from './BaseModel.js';
export { BaseModel };
export const isSharedModelGeometry = BaseModel.isSharedModelGeometry;
export const isSharedModelMaterial = BaseModel.isSharedModelMaterial;
export { createTreeModel, TreeModel } from './TreeModel.js';
export { createLogModel, LogModel } from './LogModel.js';
export { createCrocodileModel, CrocodileModel } from './CrocodileModel.js';
export { createVineModel, VineModel } from './VineModel.js';
export { createScorpionModel, ScorpionModel } from './ScorpionModel.js';
export { createBrickWallModel, BrickWallModel } from './BrickWallModel.js';
export { createCampfireModel, CampfireModel } from './CampfireModel.js';
export { createTreasureModel, TreasureModel } from './TreasureModel.js';
export { createPlayerArmsModel, PlayerArmsModel } from './PlayerArmsModel.js';
export { createOpeningQuicksandModel, OpeningQuicksandModel } from './OpeningQuicksandModel.js';
export { createSnakeModel, SnakeModel } from './SnakeModel.js';
